name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'tag for dockerhub'
        required: true
        type: environment




#env:
#  # Use docker.io for Docker Hub if empty
#  REGISTRY: docker.io
#  # github.repository as <account>/<repo>
#  IMAGE_NAME: 5wlzxep/killspiel


jobs:
  build:

    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: armv7
            distro: ubuntu20.04
          - arch: s390x
            distro: ubuntu20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses:

      - name: builds docker image
        run: docker build -t 5wlzxep/killspiel .

      - name: docker login
        run: docker login -u 5wlzxep -p ${{ secrets.TOKEN }}

      - name: docker publish
        run: docker push 5wlzxep/killspiel:${{ inputs.tag }}
